# Generated by Django 6.0 on 2025-12-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PalabraModo1',
            fields=[
                ('palabrabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.palabrabase')),
                ('palabra_dividida_letras', models.CharField(max_length=30)),
                ('tamano', models.IntegerField()),
            ],
            bases=('api.palabrabase',),
        ),
        migrations.CreateModel(
            name='PalabraModo2',
            fields=[
                ('palabrabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.palabrabase')),
                ('palabra_dividida_silabas', models.CharField(max_length=30)),
                ('silabas', models.IntegerField()),
            ],
            bases=('api.palabrabase',),
        ),
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracion_texto', models.CharField(max_length=100)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.palabrabase')),
            ],
        ),
    ]
